module.exports = [
  { city: "Los Angeles", state: "California" },
  { city: "San Francisco", state: "California" },
  { city: "San Rafael", state: "California" },
  { city: "Oakland", state: "California" },
  { city: "Truckee", state: "California" },
  { city: "San Diego", state: "California" },
  { city: "Napa", state: "California" },
  { city: "Inverness", state: "California" },
  { city: "Eureka", state: "California" },
  { city: "Crescent City", state: "California" },
  { city: "Sacramento", state: "California" },
  { city: "Tahoe", state: "California" },
  { city: "Modesto", state: "California" },
  { city: "Chico", state: "California" },
  { city: "Fresno", state: "California" },
  { city: "San Jose", state: "California" },
  { city: "Paicines", state: "California" },
  { city: "Monterey", state: "California" },
  { city: "Santa Cruz", state: "California" },
  { city: "Davenport", state: "California" },
  { city: "Pacifia", state: "California" },
  { city: "Carmel-By-The-Sea", state: "California" },
  { city: "Jenner", state: "California" },
  { city: "Barstow", state: "California" },
  { city: "Redding", state: "California" },
  { city: "Klamath", state: "California" },
  { city: "Orick", state: "California" },
  { city: "Arcata", state: "California" },
  { city: "Ontario", state: "California" },
  { city: "Burbank", state: "California" },
  { city: "Irvine", state: "California" },
  { city: "Encinitas", state: "California" },
  { city: "Camarillo", state: "California" },
  { city: "Oxnard", state: "California" },
  { city: "Santa Barbara", state: "California" },
  { city: "San Simone", state: "California" },
  { city: "Malibu", state: "California" },
  { city: "Carlsbad", state: "California" },
  { city: "San Clementine", state: "California" },
];
